spring.application.name=eureka-server
server.port=8761

# Ne pas s'auto-enregistrer ni chercher d'autres serveurs Eureka
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false
eureka.server.wait-time-in-ms-when-sync-empty=0

logging.level.com.netflix.eureka=OFF
logging.level.com.netflix.discovery=OFF
